### ISSUE TITLE
Style berishdagi hatolar

### ISSUE THREAD

**Issue by otabek-oktamov** [Mr-Perfectuz/Intro#1]
![Screenshot_33](https://user-images.githubusercontent.com/79497492/140328378-cd69c15b-f89d-41f2-bdb2-931d1a320195.png)
bu yerda margin a tegining ustiga chiqib ketyapti buni oldini olish uchun .hero-link ga display:inline-block berilishi kerak

**Comment by Mr-Perfectuz** [comment]
inline-block berildi
